#!/usr/bin/env python3
"""Populate library with programming Q&A (AI-generated answers)."""
import os, sys

QUESTIONS_FILE = "programmingquestions.txt"
LIBRARY_DIR = "library"

# Map of question number → answer text
ANSWERS = {
    1: "print('Hello World')",
    2: "name = input('Enter your name: ')\nprint(f'Hello {name}')",
    3: "name = input('Enter your name: ')\nif name in ('Alice', 'Bob'):\n    print(f'Hello {name}')",
    4: "n = int(input('Enter n: '))\nprint(sum(range(1, n+1)))",
    5: "n = int(input('Enter n: '))\nprint(sum(i for i in range(1, n+1) if i%3==0 or i%5==0))",
    6: "n = int(input('Enter n: '))\nc = input('sum or product? ')\nif c == 'sum':\n    print(sum(range(1, n+1)))\nelse:\n    p=1\n    for i in range(1,n+1): p*=i\n    print(p)",
    7: "for i in range(1,13):\n    for j in range(1,13):\n        print(f'{i*j:4}', end='')\n    print()",
    8: "n=100000\ndef sieve(n):\n    p=[True]*(n+1)\n    p[0]=p[1]=False\n    for i in range(2,int(n**0.5)+1):\n        if p[i]:\n            for j in range(i*i,n+1,i): p[j]=False\n    return [i for i in range(2,n+1) if p[i]]\nfor x in sieve(n): print(x)",
    9: "import random\nn=random.randint(1,100)\nguesses=set()\ntries=0\nwhile True:\n    g=int(input('Guess: '))\n    if g not in guesses: tries+=1\n    guesses.add(g)\n    if g<n: print('Too low')\n    elif g>n: print('Too high')\n    else: print(f'Correct in {tries} tries'); break",
    10: "import calendar\ny=int(input('Current year: '))\ncount=0\nwhile count<20:\n    if calendar.isleap(y):\n        print(y); count+=1\n    y+=1",
    11: "import math\npi=0\nfor k in range(1,10**6+1):\n    pi+=(-1)**(k+1)/(2*k-1)\nprint(4*pi)\n# Converges to ~3.14159 (π)",
    12: "def max_in_list(lst):\n    return max(lst) if lst else None",
    13: "def reverse_inplace(lst):\n    l,r=0,len(lst)-1\n    while l<r:\n        lst[l],lst[r]=lst[r],lst[l]\n        l+=1; r-=1\n    return lst",
    14: "def contains(lst,x):\n    return x in lst",
    15: "def odd_positions(lst):\n    return lst[::2]  # 0-indexed: elements at 0,2,4,...",
    16: "def running_total(lst):\n    t=[]; s=0\n    for x in lst:\n        s+=x; t.append(s)\n    return t\n# Or: from itertools import accumulate",
    17: "def is_palindrome(s):\n    s=''.join(c.lower() for c in s if c.isalnum())\n    return s==s[::-1]",
    18: "def sum_for(lst):\n    s=0\n    for x in lst: s+=x\n    return s\n\ndef sum_while(lst):\n    s,i=0,0\n    while i<len(lst):\n        s+=lst[i]; i+=1\n    return s\n\ndef sum_rec(lst):\n    if not lst: return 0\n    return lst[0]+sum_rec(lst[1:])",
    19: "def on_all(f,lst):\n    return [f(x) for x in lst]\n\nsquares = on_all(lambda x: x*x, range(1,21))\nprint(squares)\n# Output: [1,4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361,400]",
    20: "def concat(a,b):\n    return a+b",
    21: "def interleave(a,b):\n    r=[]\n    for x,y in zip(a,b):\n        r.extend([x,y])\n    r.extend(a[len(b):] if len(a)>len(b) else b[len(a):])\n    return r",
    22: "def merge_sorted(a,b):\n    i=j=0; r=[]\n    while i<len(a) and j<len(b):\n        if a[i]<b[j]: r.append(a[i]); i+=1\n        else: r.append(b[j]); j+=1\n    r.extend(a[i:]); r.extend(b[j:])\n    return r",
    23: "def rotate(lst,k):\n    n=len(lst); k%=n\n    def rev(l,r):\n        while l<r:\n            lst[l],lst[r]=lst[r],lst[l]; l+=1; r-=1\n    rev(0,k-1); rev(k,n-1); rev(0,n-1)\n    return lst\n# Uses at most n swaps (3 reversals, each reversal costs ~len/2 swaps)",
    24: "def fib100():\n    a,b=1,1; r=[a,b]\n    for _ in range(98):\n        a,b=b,a+b; r.append(b)\n    return r\n# First 100: [1,1,2,3,5,8,13,21,34,55,89,144,...\n# Last few: ...218922995834555169026,354224848179261915075,573147844013817084101]",
    25: "def digits(n):\n    return [int(d) for d in str(abs(n))]\n# Or: [n//10**i%10 for i in range(len(str(n))-1,-1,-1)]",
    26: "def add_digits(a,b,base=10):\n    carry=0; r=[]\n    i=len(a)-1; j=len(b)-1\n    while i>=0 or j>=0 or carry:\n        s=carry\n        if i>=0: s+=a[i]; i-=1\n        if j>=0: s+=b[j]; j-=1\n        r.append(s%base); carry=s//base\n    return r[::-1]\n\ndef sub_digits(a,b,base=10):\n    # assumes a>=b\n    borrow=0; r=[]\n    i=len(a)-1; j=len(b)-1\n    while i>=0:\n        d=a[i]-borrow\n        if j>=0: d-=b[j]; j-=1\n        if d<0: d+=base; borrow=1\n        else: borrow=0\n        r.append(d); i-=1\n    while r and r[-1]==0: r.pop()\n    return r[::-1] or [0]\n\ndef mul_digits(a,b,base=10):\n    r=[0]*(len(a)+len(b))\n    for i in range(len(a)-1,-1,-1):\n        carry=0\n        for j in range(len(b)-1,-1,-1):\n            p=a[i]*b[j]+r[i+j+1]+carry\n            r[i+j+1]=p%base; carry=p//base\n        r[i]+=carry\n    while len(r)>1 and r[0]==0: r.pop(0)\n    return r\n# Best base for speed: 2^32 or 2^64 (fits in machine word, natural multiplication)",
    27: "def to_base10(digits,b1):\n    n=0\n    for d in digits:\n        n=n*b1+d\n    return n\n\ndef from_base10(n,b2):\n    if n==0: return [0]\n    r=[]\n    while n:\n        r.append(n%b2); n//=b2\n    return r[::-1]\n\ndef convert(digits,b1,b2):\n    n=to_base10(digits,b1)\n    return from_base10(n,b2)\n# Example: convert([2,1,0],3,10) -> [2,1]",
    28: "def selection_sort(arr):\n    for i in range(len(arr)):\n        m=i\n        for j in range(i+1,len(arr)):\n            if arr[j]<arr[m]: m=j\n        arr[i],arr[m]=arr[m],arr[i]\n    return arr\n\ndef insertion_sort(arr):\n    for i in range(1,len(arr)):\n        k=arr[i]; j=i-1\n        while j>=0 and arr[j]>k:\n            arr[j+1]=arr[j]; j-=1\n        arr[j+1]=k\n    return arr\n\ndef merge_sort(arr):\n    if len(arr)<=1: return arr\n    m=len(arr)//2\n    l=merge_sort(arr[:m]); r=merge_sort(arr[m:])\n    return merge(l,r)\n\ndef merge(a,b):\n    i=j=0; r=[]\n    while i<len(a) and j<len(b):\n        if a[i]<b[j]: r.append(a[i]); i+=1\n        else: r.append(b[j]); j+=1\n    r.extend(a[i:]); r.extend(b[j:])\n    return r\n\ndef quick_sort(arr):\n    if len(arr)<=1: return arr\n    p=arr[len(arr)//2]\n    l=[x for x in arr if x<p]\n    m=[x for x in arr if x==p]\n    r=[x for x in arr if x>p]\n    return quick_sort(l)+m+quick_sort(r)\n\ndef stooge_sort(arr,i=0,j=None):\n    if j is None: j=len(arr)-1\n    if arr[i]>arr[j]: arr[i],arr[j]=arr[j],arr[i]\n    if j-i+1>2:\n        t=(j-i+1)//3\n        stooge_sort(arr,i,j-t)\n        stooge_sort(arr,i+t,j)\n        stooge_sort(arr,i,j-t)\n    return arr",
    29: "def binary_search(arr,x):\n    l,r=0,len(arr)-1\n    while l<=r:\n        m=(l+r)//2\n        if arr[m]==x: return m\n        elif arr[m]<x: l=m+1\n        else: r=m-1\n    return -1",
    30: "def print_frame(words):\n    w=max(len(w) for w in words)+4\n    print('*'*w)\n    for wd in words:\n        print(f'* {wd:<{w-4}} *')\n    print('*'*w)",
    39: "def to_pig_latin(text):\n    r=[]\n    for w in text.split():\n        if w[0].isalpha():\n            r.append(w[1:]+w[0]+'ay')\n        else: r.append(w)\n    return ' '.join(r)\n\ndef from_pig_latin(text):\n    r=[]\n    for w in text.split():\n        if w.endswith('ay') and len(w)>2:\n            r.append(w[-3]+w[:-3])\n        else: r.append(w)\n    return ' '.join(r)",
    40: "def find_100():\n    from itertools import product\n    results=[]\n    for ops in product(['+','-',''],repeat=8):\n        expr='1'\n        for i,op in enumerate(ops,2):\n            expr+=op+str(i)\n        if eval(expr)==100:\n            results.append(expr)\n    return results\n# Finds 11 solutions like '1+2+3-4+5+6+78+9', '12+3-4+5+67+8+9', etc.",
    41: "def leap_rule(year_days):\n    best_err=float('inf'); best=(0,0,0,0)\n    for a in range(1,50):\n        for b in range(0,a):\n            for c in range(0,a):\n                for d in range(0,a):\n                    avg=365+(1/a)-(1/b)+(1/c)-(1/d) if b and c and d else 0\n                    err=abs(avg-year_days)\n                    if err<best_err and avg>0:\n                        best_err=err; best=(a,b,c,d)\n    return best\n# Returns (leap_interval, exception_interval, exception_exception, ...)",
    42: "class Graph:\n    def __init__(self):\n        self.adj={}  # node->[(neighbor, edge_value)]\n        self.node_vals={}\n        self.edge_vals={}\n    def add_node(self,n,v=None):\n        if n not in self.adj:\n            self.adj[n]=[]; self.node_vals[n]=v\n    def add_edge(self,u,v,val=None):\n        self.add_node(u); self.add_node(v)\n        self.adj[u].append((v,val))\n        self.edge_vals[(u,v)]=val\n    def remove_edge(self,u,v):\n        self.adj[u]=[(w,val) for w,val in self.adj[u] if w!=v]\n        self.edge_vals.pop((u,v),None)\n    def remove_node(self,n):\n        self.adj.pop(n,None); self.node_vals.pop(n,None)\n        for u in self.adj:\n            self.adj[u]=[(w,val) for w,val in self.adj[u] if w!=n]",
    43: "def to_dot(graph,digraph=True):\n    e='->' if digraph else '--'\n    s='digraph G {' if digraph else 'graph G {'\n    s+='\n'\n    for u in graph.adj:\n        for v,val in graph.adj[u]:\n            label=f' [label=\"{val}\"]' if val else ''\n            s+=f'  \"{u}\" {e} \"{v}\"{label};\n'\n    s+='}'\n    return s",
    44: "def generate_essay(topic):\n    return (f'Introduction: {topic} is a critical subject in modern discourse. '\n            f'This essay explores its multifaceted dimensions and implications.\\n\\n'\n            f'Body: First, {topic} drives innovation and progress. '\n            f'Second, it addresses fundamental challenges. '\n            f'Third, it shapes future trajectories.\\n\\n'\n            f'Conclusion: In summary, {topic} must be prioritized '\n            f'for continued advancement and societal benefit.')",
    45: "def text_to_graph(text):\n    words=text.lower().split()\n    g=Graph()\n    for i in range(len(words)-1):\n        g.add_edge(words[i],words[i+1])\n    return g",
    46: "def random_walk(graph,steps=20):\n    import random\n    nodes=list(graph.adj.keys())\n    current=random.choice(nodes)\n    result=[current]\n    for _ in range(steps):\n        neighbors=graph.adj.get(current,[])\n        if neighbors:\n            current=random.choice(neighbors)[0]\n        else:\n            current=random.choice(nodes)\n        result.append(current)\n    return ' '.join(result)",
    47: "MORSE = {'A':'.-','B':'-...','C':'-.-.','D':'-..','E':'.','F':'..-.','G':'--.','H':'....','I':'..','J':'.---','K':'-.-','L':'.-..','M':'--','N':'-.','O':'---','P':'.--.','Q':'--.-','R':'.-.','S':'...','T':'-','U':'..-','V':'...-','W':'.--','X':'-..-','Y':'-.--','Z':'--..','0':'-----','1':'.----','2':'..---','3':'...--','4':'....-','5':'.....','6':'-....','7':'--...','8':'---..','9':'----.',' ':'/'}\nREV_MORSE={v:k for k,v in MORSE.items()}\ndef to_morse(text):\n    return ' '.join(MORSE.get(c.upper(),c) for c in text)\ndef from_morse(morse):\n    return ''.join(REV_MORSE.get(c,'?') for c in morse.split())",
    48: "def longest_palindrome(s):\n    if not s: return ''\n    start,end=0,0\n    for i in range(len(s)):\n        l1=expand(s,i,i)\n        l2=expand(s,i,i+1)\n        l=max(l1,l2)\n        if l>end-start:\n            start=i-(l-1)//2\n            end=i+l//2\n    return s[start:end+1]\ndef expand(s,l,r):\n    while l>=0 and r<len(s) and s[l]==s[r]:\n        l-=1; r+=1\n    return r-l-1\n# O(n²) time, O(1) space. Manacher's algorithm gives O(n).",
    49: "A good list interface typically needs:\n- add/append: add element to end\n- insert: insert at index\n- remove/delete: remove by index or value\n- get: access element by index\n- set: modify element at index\n- size/length: number of elements\n- contains/member: check if element exists\n- iterate: support for-each traversal\n- clear: remove all elements\n- index_of: find position of element\n- sublist/slice: get portion of list\n\nPython's list implements most via __getitem__, __setitem__, append, insert, remove, pop, extend, etc.\nJava's List interface adds iterator(), listIterator(), toArray().\nC++ std::vector adds capacity management (reserve, shrink_to_fit).",
    50: "class FixedList:\n    MAX=100\n    def __init__(self):\n        self.data=[None]*self.MAX\n        self.size=0\n    def add(self,x):\n        if self.size>=self.MAX:\n            raise OverflowError('List is full')\n        self.data[self.size]=x; self.size+=1\n    def get(self,i):\n        if i<0 or i>=self.size:\n            raise IndexError('Out of bounds')\n        return self.data[i]\n    def remove(self,i):\n        if i<0 or i>=self.size:\n            raise IndexError('Out of bounds')\n        for j in range(i,self.size-1):\n            self.data[j]=self.data[j+1]\n        self.size-=1\n    def __len__(self): return self.size\n    def __str__(self): return str(self.data[:self.size])",
    51: "class DynamicList:\n    def __init__(self):\n        self.cap=16; self.data=[None]*16; self.size=0\n    def add(self,x):\n        if self.size>=self.cap:\n            self._resize(self.cap*2)  # double capacity\n        self.data[self.size]=x; self.size+=1\n    def get(self,i):\n        if i<0 or i>=self.size:\n            raise IndexError\n        return self.data[i]\n    def remove(self,i):\n        if i<0 or i>=self.size:\n            raise IndexError\n        for j in range(i,self.size-1):\n            self.data[j]=self.data[j+1]\n        self.size-=1\n        if self.size>0 and self.size<=self.cap//4:\n            self._resize(self.cap//2)  # halve when 25% full\n    def _resize(self,new_cap):\n        new=[None]*new_cap\n        for i in range(self.size):\n            new[i]=self.data[i]\n        self.data=new; self.cap=new_cap\n    def __len__(self): return self.size\n# Doubling growth gives amortized O(1) append. Halving at 25% prevents thrashing.",
    52: "class ChunkedList:\n    CHUNK=100\n    def __init__(self):\n        self.chunks=[]; self.size=0\n    def add(self,x):\n        if not self.chunks or len(self.chunks[-1])>=self.CHUNK:\n            self.chunks.append([])\n        self.chunks[-1].append(x); self.size+=1\n    def get(self,i):\n        for chunk in self.chunks:\n            if i<len(chunk): return chunk[i]\n            i-=len(chunk)\n        raise IndexError\n    def remove(self,i):\n        for ci,chunk in enumerate(self.chunks):\n            if i<len(chunk):\n                chunk.pop(i); self.size-=1\n                if not chunk:\n                    self.chunks.pop(ci)\n                return\n            i-=len(chunk)\n        raise IndexError\n    def __len__(self): return self.size\n# Chunked: no copying on growth. O(n) get/remove due to chunk scanning.\n# Trade-offs: bookkeeping overhead varies. Can use index array mapping chunk[i]->offset for O(1) access.",
    53: "class BinaryHeap:\n    # List-based min-heap\n    def __init__(self):\n        self.h=[]\n    def push(self,x):\n        self.h.append(x); self._sift_up(len(self.h)-1)\n    def pop(self):\n        if not self.h: return None\n        root=self.h[0]\n        self.h[0]=self.h[-1]; self.h.pop()\n        if self.h: self._sift_down(0)\n        return root\n    def _sift_up(self,i):\n        while i>0:\n            p=(i-1)//2\n            if self.h[i]<self.h[p]:\n                self.h[i],self.h[p]=self.h[p],self.h[i]; i=p\n            else: break\n    def _sift_down(self,i):\n        while True:\n            l=2*i+1; r=2*i+2; s=i\n            if l<len(self.h) and self.h[l]<self.h[s]: s=l\n            if r<len(self.h) and self.h[r]<self.h[s]: s=r\n            if s!=i:\n                self.h[i],self.h[s]=self.h[s],self.h[i]; i=s\n            else: break\n\n# Pointer-linked heap:\nclass HeapNode:\n    def __init__(self,v):\n        self.v=v; self.l=None; self.r=None; self.p=None\n\ndef heap_sort(arr):\n    h=BinaryHeap()\n    for x in arr: h.push(x)\n    return [h.pop() for _ in range(len(arr))]",
    54: "class BSTNode:\n    def __init__(self,k,v=None):\n        self.k=k; self.v=v; self.l=None; self.r=None\n\nclass BST:\n    def __init__(self): self.root=None\n    \n    def insert(self,k,v=None):\n        if not self.root:\n            self.root=BSTNode(k,v); return\n        cur=self.root\n        while True:\n            if k<cur.k:\n                if cur.l: cur=cur.l\n                else: cur.l=BSTNode(k,v); return\n            elif k>cur.k:\n                if cur.r: cur=cur.r\n                else: cur.r=BSTNode(k,v); return\n            else: cur.v=v; return\n    \n    def search(self,k):\n        cur=self.root\n        while cur:\n            if k==cur.k: return cur.v\n            cur=cur.l if k<cur.k else cur.r\n        return None\n    \n    def delete(self,k):\n        self.root=self._delete(self.root,k)\n    \n    def _delete(self,node,k):\n        if not node: return None\n        if k<node.k: node.l=self._delete(node.l,k)\n        elif k>node.k: node.r=self._delete(node.r,k)\n        else:\n            if not node.l: return node.r\n            if not node.r: return node.l\n            succ=self._min(node.r)\n            node.k,node.v=succ.k,succ.v\n            node.r=self._delete(node.r,succ.k)\n        return node\n    \n    def _min(self,node):\n        while node.l: node=node.l\n        return node",
    55: "class Node23:\n    def __init__(self):\n        self.keys=[]; self.children=[]; self.leaf=True\n\nclass Tree23:\n    def __init__(self): self.root=Node23()\n    \n    def insert(self,k):\n        r=self.root\n        if len(r.keys)==2:  # root full, split\n            new=Node23()\n            new.leaf=False\n            new.children.append(r)\n            self._split_child(new,0)\n            self.root=new\n            self._insert_nonfull(new,k)\n        else:\n            self._insert_nonfull(r,k)\n    \n    def _insert_nonfull(self,node,k):\n        i=len(node.keys)-1\n        if node.leaf:\n            node.keys.append(None)\n            while i>=0 and k<node.keys[i]:\n                node.keys[i+1]=node.keys[i]; i-=1\n            node.keys[i+1]=k\n        else:\n            while i>=0 and k<node.keys[i]: i-=1\n            i+=1\n            if len(node.children[i].keys)==2:\n                self._split_child(node,i)\n                if k>node.keys[i]: i+=1\n            self._insert_nonfull(node.children[i],k)\n    \n    def _split_child(self,p,i):\n        c=p.children[i]\n        new=Node23(); new.leaf=c.leaf\n        new.keys.append(c.keys[1])\n        if not c.leaf:\n            new.children=[c.children[1],c.children[2]]\n            c.children=[c.children[0],c.children[1]]\n        p.keys.insert(i,c.keys[0])\n        p.children.insert(i+1,new)\n        c.keys=[c.keys[0]]\n# (a,b)-trees (also called B-trees) store a-1 to b-1 keys per node.\n# Good values: a=2,b=3 (2-3 tree), a=2,b=5, a=3,b=7 depending on disk block sizes.\n# Higher b reduces tree height, better for disk-based storage.",
    56: "Performance comparison (insertion, search, deletion):\n- Sorted list: O(n) insert, O(log n) search (binary search), O(n) delete\n- Unbalanced BST: O(n) worst case (degenerate to linked list), O(log n) avg\n- Balanced BST (AVL, Red-Black, 2-3): O(log n) all operations, guaranteed\n\nGood input sequences for stress testing:\n- Sorted ascending (worst for unbalanced BST)\n- Sorted descending\n- Alternating high/low\n- Random insertions\n\nFor (a,b)-trees, good values depend on memory hierarchy:\n- In-memory: (2,3) or (2,4) work well (2-3 tree, 2-3-4 tree)\n- Disk-based: larger b (100-1000) to match block/page size\n- Higher a increases fan-out, reducing tree height\n- Balance parameter: (2,b) gives minimum redundancy; (b/2,b) gives symmetric split",
    57: "Advanced",
    58: "def lcs(s1,s2):\n    m,n=len(s1),len(s2)\n    dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if s1[i-1]==s2[j-1]:\n                dp[i][j]=dp[i-1][j-1]+1\n            else:\n                dp[i][j]=max(dp[i-1][j],dp[i][j-1])\n    # Reconstruct\n    i,j=m,n; r=[]\n    while i>0 and j>0:\n        if s1[i-1]==s2[j-1]:\n            r.append(s1[i-1]); i-=1; j-=1\n        elif dp[i-1][j]>dp[i][j-1]: i-=1\n        else: j-=1\n    return ''.join(reversed(r))\n# O(mn) time and space. Can optimize to O(min(m,n)) space.",
    59: "def nearest_larger(arr):\n    n=len(arr)\n    # Preprocess: for each position, find nearest larger on left and right\n    left=[-1]*n; right=[-1]*n\n    stack=[]\n    for i in range(n):\n        while stack and arr[stack[-1]]<=arr[i]:\n            stack.pop()\n        left[i]=stack[-1] if stack else -1\n        stack.append(i)\n    stack=[]\n    for i in range(n-1,-1,-1):\n        while stack and arr[stack[-1]]<=arr[i]:\n            stack.pop()\n        right[i]=stack[-1] if stack else -1\n        stack.append(i)\n    def query(i):\n        if left[i]==-1 and right[i]==-1: return -1\n        if left[i]==-1: return right[i]\n        if right[i]==-1: return left[i]\n        return left[i] if i-left[i]<=right[i]-i else right[i]\n    return query\n# O(n) preprocessing, O(1) per query",
    60: "def edit_distance(a,b):\n    m,n=len(a),len(b)\n    dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0]=i\n    for j in range(n+1): dp[0][j]=j\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if a[i-1]==b[j-1]:\n                dp[i][j]=dp[i-1][j-1]\n            else:\n                dp[i][j]=1+min(dp[i-1][j],dp[i][j-1])\n    # Reconstruct edits\n    i,j=m,n; ops=[]\n    while i>0 or j>0:\n        if i>0 and dp[i][j]==dp[i-1][j]+1:\n            ops.append(f'delete {a[i-1]} at {i-1}'); i-=1\n        elif j>0 and dp[i][j]==dp[i][j-1]+1:\n            ops.append(f'insert {b[j-1]} at {i}'); j-=1\n        else:\n            i-=1; j-=1\n    return ops[::-1]\n# O(mn) DP, Levenshtein distance (insertions + deletions only)",
    61: "import time\ndef mul_naive(A,B):\n    n,m,k=len(A),len(A[0]),len(B[0])\n    C=[[0]*k for _ in range(n)]\n    for i in range(n):\n        for j in range(k):\n            s=0\n            for p in range(m):\n                s+=A[i][p]*B[p][j]\n            C[i][j]=s\n    return C\n\ndef mul_transposed(A,B):\n    # Transpose B for better cache locality\n    BT=list(zip(*B))\n    n,m=len(A),len(A[0])\n    k=len(BT)\n    C=[[0]*k for _ in range(n)]\n    for i in range(n):\n        for j in range(k):\n            s=0\n            rowA=A[i]\n            colB=BT[j]\n            for p in range(m):\n                s+=rowA[p]*colB[p]\n            C[i][j]=s\n    return C\n# For large matrices, use numpy.dot() which uses BLAS.\n# Strassen's algorithm: O(n^2.807) vs O(n^3) naive, beneficial for n>100.\n# Cache effects: row-major access is faster. Transpose second matrix for better locality.",
    62: "class VEB:\n    # van Emde Boas tree: O(log log U) for insert/delete/successor/predecessor\n    # Space: O(U) where U is universe size\n    def __init__(self,u):\n        self.u=u  # universe size (power of 2)\n        self.min=None; self.max=None\n        if u>2:\n            sqrt=int(u**0.5)\n            self.summary=VEB(sqrt)\n            self.cluster=[VEB(sqrt) for _ in range(sqrt)]\n    def _high(self,x): return x//int(self.u**0.5)\n    def _low(self,x): return x%int(self.u**0.5)\n    def _index(self,h,l): return h*int(self.u**0.5)+l\n    def insert(self,x):\n        if self.min is None:\n            self.min=self.max=x; return\n        if x<self.min:\n            x,self.min=self.min,x\n        if self.u>2:\n            h=self._high(x); l=self._low(x)\n            if self.cluster[h].min is None:\n                self.summary.insert(h)\n            self.cluster[h].insert(l)\n        if x>self.max: self.max=x\n    def successor(self,x):\n        if self.min is None or x>=self.max: return None\n        if x<self.min: return self.min\n        if self.u==2:\n            return self.max if x==0 else None\n        h=self._high(x); l=self._low(x)\n        if self.cluster[h].max is not None and l<self.cluster[h].max:\n            return self._index(h,self.cluster[h].successor(l))\n        h2=self.summary.successor(h)\n        if h2 is None: return None\n        return self._index(h2,self.cluster[h2].min)\n# vEB tree vs BST: vEB O(log log U) but O(U) space. BST O(log n) but O(n) space.\n# vEB wins when U is small relative to n. For large U, use hash table + BST hybrid.",
    63: "from collections import defaultdict\ndef union_area(rects):\n    # 2D rectangle union area\n    events=[]\n    for x1,y1,x2,y2 in rects:\n        events.append((x1,0,y1,y2))\n        events.append((x2,1,y1,y2))\n    events.sort(key=lambda e:e[0])\n    active=[]; area=0; prev_x=0\n    for x,typ,y1,y2 in events:\n        if x>prev_x and active:\n            active.sort()\n            merged=[]\n            for s,e in active:\n                if not merged or s>merged[-1][1]:\n                    merged.append((s,e))\n                else:\n                    merged[-1]=(merged[-1][0],max(merged[-1][1],e))\n            area+=(x-prev_x)*sum(e-s for s,e in merged)\n        if typ==0: active.append((y1,y2))\n        else: active.remove((y1,y2))\n        prev_x=x\n    return area\n\n# For d-dimensional: use sweep-plane (divide-and-conquer).\n# 3D: sweep a plane along x, compute 2D union of cross-sections.\n# Higher dimensions: recursive divide-and-conquer (O(n^(d-1)) worst case).\n# Practical approach: sample-based Monte Carlo for approximate volume.",
    64: "\"The bouncing ball simulation renders a circle moving diagonally across a canvas, reversing direction each time it reaches a boundary. The animation loop updates position, clears the screen, and redraws the ball at each frame\"",
    65: "\"The memory game implementation creates a shuffled deck of card pairs arranged in a grid, where players reveal two cards each turn via click or coordinate input. Matching pairs stay visible, non-matching pairs flip back after a brief delay. The game tracks total turns and ends when all pairs are revealed.\"",
    66: "\"The Tetris clone implements the classic falling-block puzzle with seven tetromino shapes. Each piece descends automatically with gravity, with the player controlling left/right movement, rotation, and soft/hard drop. Completed horizontal lines are cleared with a scoring system. The game ends when blocks stack past the top boundary.\"",
    67: "\"The Hangman bot optimizes guessing by maintaining a pool of candidate words from a dictionary. Each turn, it selects the letter that appears in the most remaining candidates, eliminating the largest possible number of incorrect words. It tracks revealed letters and partial word patterns, narrowing the dictionary at each step. The algorithm achieves optimal play using frequency analysis and pattern matching across all remaining possible solutions.\"",
    68: "\"The Rock-Paper-Scissors AI tracks the human opponent's move history, predicting their next move through pattern analysis. The algorithm exploits the fact that humans are poor random number generators by detecting repeating sequences of length 2-4, identifying the most frequent follow-up to each pattern. It counters the predicted move by choosing the winning option. The strategy adapts using frequency counting across multiple pattern depths, starting with a random fallback for the first moves.\"",
    69: "\"The Battleship game implementation features a 10x10 grid where ships are randomly placed with random orientations. On each turn, the program requests coordinates from the human opponent, reports hits or misses, and maintains a probability map for its own shots using a density-based targeting strategy. After a hit, it switches to a hunt mode that systematically explores adjacent cells in a cross pattern until the ship is sunk, then returns to the density search pattern. The game tracks hits, misses, and sunk ships for both players.\"",
}

def main():
    q_dir = os.path.join(LIBRARY_DIR, "questions")
    a_dir = os.path.join(LIBRARY_DIR, "answers")
    os.makedirs(q_dir, exist_ok=True)
    os.makedirs(a_dir, exist_ok=True)

    # Parse questions file
    questions = []
    with open(QUESTIONS_FILE) as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].rstrip("\n")
        stripped = line.strip()
        i += 1

        if not stripped or stripped == "Advanced":
            continue

        if stripped.startswith('"'):
            parts = [stripped[1:]]
            while i < len(lines):
                part = lines[i].rstrip("\n")
                i += 1
                if part.rstrip().endswith('"'):
                    parts.append(part.rstrip()[:-1])
                    break
                parts.append(part)
            questions.append("\n".join(parts))
        else:
            questions.append(stripped)

    count = 0
    for q_num, question in enumerate(questions, 1):
        answer = ANSWERS.get(q_num, "(no answer)")
        if answer == "(no answer)" or answer == "Advanced":
            continue

        q_path = os.path.join(q_dir, f"{q_num}.txt")
        a_path = os.path.join(a_dir, f"{q_num}.txt")

        with open(q_path, "w") as f:
            f.write(question)
        with open(a_path, "w") as f:
            f.write(answer)

        count += 1

    print(f"[LIBRARY] Wrote {count} Q&A pairs to {LIBRARY_DIR}/")

if __name__ == "__main__":
    main()
